"""
Social Authentication API Endpoints

REST API endpoints for OAuth 2.0 social login (Google, GitHub, etc.)
Implements Authorization Code Flow with PKCE for secure authentication.
"""

from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from fastapi.responses import RedirectResponse
from sqlalchemy.orm import Session
from typing import Optional

from src.core.database import get_db
from src.repositories.auth_repository import AuthRepository
from src.repositories.profile_repository import ProfileRepository
from src.repositories.audit_repository import AuditRepository
from src.services.social_auth_service import (
    SocialAuthService,
    OAuthProviderNotConfiguredError,
    OAuthStateValidationError,
    OAuthTokenExchangeError,
    OAuthTokenVerificationError,
    AccountLinkingError
)
from src.services.audit_service import AuditService
from src.schemas.auth import LoginResponse


router = APIRouter(prefix="/social", tags=["Social Authentication"])


def get_social_auth_service(db: Session = Depends(get_db)) -> SocialAuthService:
    """
    Dependency to get SocialAuthService instance.

    Creates service with auth, profile repositories and audit service.
    """
    auth_repo = AuthRepository(db)
    profile_repo = ProfileRepository(db)
    audit_repo = AuditRepository(db)
    audit_service = AuditService(audit_repo)
    return SocialAuthService(auth_repo, profile_repo, audit_service=audit_service)


@router.post(
    "/{provider}/authorize",
    status_code=status.HTTP_200_OK,
    summary="Generate OAuth Authorization URL",
    description="Generate OAuth 2.0 authorization URL with PKCE for social login"
)
def authorize(
    provider: str,
    http_request: Request,
    response: Response,
    service: SocialAuthService = Depends(get_social_auth_service)
):
    """
    Generate OAuth Authorization URL

    Creates an OAuth 2.0 authorization URL for the specified provider with PKCE.
    The client must store the returned code_verifier in sessionStorage and redirect
    the user to the authorization_url.

    **Supported Providers:**
    - google: Google OAuth 2.0

    **PKCE Security:**
    - code_verifier: Random string generated by server, stored in client session
    - code_challenge: SHA-256 hash of code_verifier, sent to provider
    - Prevents authorization code interception attacks

    **CSRF Protection:**
    - state: Random string to prevent CSRF attacks
    - Client must verify state matches in callback

    **Example Response:**
    ```json
    {
      "authorization_url": "https://accounts.google.com/o/oauth2/v2/auth?...",
      "state": "random-state-value",
      "code_verifier": "random-verifier-value"
    }
    ```

    **Client Flow:**
    1. Call this endpoint to get authorization URL, state, and code_verifier
    2. Store code_verifier and state in sessionStorage (NOT localStorage)
    3. Redirect user to authorization_url
    4. User authenticates with provider and grants consent
    5. Provider redirects to callback URL with code and state
    6. Client calls callback endpoint with code, state, and code_verifier

    **Errors:**
    - 400: Invalid provider or provider not configured
    - 500: Failed to generate authorization URL
    """
    try:
        # Generate authorization URL with PKCE
        authorization_url, state, code_verifier = service.generate_authorization_url(provider)

        return {
            "authorization_url": authorization_url,
            "state": state,
            "code_verifier": code_verifier,
            "message": f"Redirect user to authorization_url. Store code_verifier and state in sessionStorage."
        }

    except OAuthProviderNotConfiguredError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "code": "oauth_not_configured",
                "message": str(e),
                "provider": provider
            }
        )
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "code": "invalid_provider",
                "message": str(e),
                "provider": provider
            }
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "code": "authorization_url_failed",
                "message": f"Failed to generate authorization URL: {str(e)}"
            }
        )


@router.get(
    "/{provider}/callback",
    response_model=LoginResponse,
    summary="OAuth Callback Endpoint",
    description="Handle OAuth 2.0 provider callback and issue JWT tokens"
)
async def callback(
    provider: str,
    code: str,
    state: str,
    code_verifier: str,
    expected_state: str,
    http_request: Request,
    service: SocialAuthService = Depends(get_social_auth_service)
):
    """
    OAuth Callback Endpoint

    Handles OAuth 2.0 provider callback, verifies authorization code, and issues JWT tokens.

    **Query Parameters:**
    - code: Authorization code from provider
    - state: State parameter from provider (CSRF protection)
    - code_verifier: PKCE code verifier from client sessionStorage
    - expected_state: Expected state value from client sessionStorage

    **Process:**
    1. Validate state parameter (CSRF protection)
    2. Exchange authorization code for access token and ID token
    3. Verify ID token signature using provider's public keys
    4. Extract user info from ID token (email, name, provider_id)
    5. Create new user or authenticate existing OAuth user
    6. Issue custom JWT access and refresh tokens
    7. Return tokens with user metadata

    **Account Linking:**
    - If email exists with email/password auth: Reject with account_linking_required error
    - If OAuth account exists: Authenticate directly
    - Otherwise: Create new account with OAuth credentials

    **Example Response:**
    ```json
    {
      "access_token": "eyJhbGc...",
      "refresh_token": "eyJhbGc...",
      "token_type": "bearer",
      "expires_in": 1800,
      "user_id": "uuid-here",
      "email": "user@gmail.com",
      "is_new_user": true
    }
    ```

    **Errors:**
    - 400: Invalid state (CSRF attack attempt)
    - 400: Token exchange failed
    - 400: ID token verification failed
    - 409: Account linking required (email exists)
    - 500: Unexpected error
    """
    try:
        # Extract client IP and user agent for audit
        client_ip = http_request.client.host if http_request.client else None
        user_agent = http_request.headers.get("User-Agent")

        # Exchange authorization code for tokens
        token_response = service.exchange_code_for_token(
            provider=provider,
            code=code,
            code_verifier=code_verifier,
            state=state,
            expected_state=expected_state
        )

        # Extract ID token
        id_token = token_response.get("id_token")
        if not id_token:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail={
                    "code": "missing_id_token",
                    "message": "Provider did not return ID token"
                }
            )

        # Verify and decode ID token
        claims = service.verify_google_id_token(id_token)

        # Extract user info from claims
        provider_id = claims.get("sub")  # Google user ID
        email = claims.get("email")
        display_name = claims.get("name", email)  # Fallback to email if name not provided
        email_verified = claims.get("email_verified", False)

        # Authenticate or create user
        access_token, refresh_token, user_id, is_new_user, account_type, is_email_verified, is_admin = service.authenticate_or_create_user(
            provider=provider,
            provider_id=provider_id,
            email=email,
            display_name=display_name,
            email_verified=email_verified,
            ip_address=client_ip,
            user_agent=user_agent
        )

        # Return JWT tokens (same format as email/password login)
        return LoginResponse(
            access_token=access_token,
            refresh_token=refresh_token,
            token_type="bearer",
            expires_in=1800,  # 30 minutes
            user_id=user_id,
            email=email,
            is_email_verified=is_email_verified,
            account_type=account_type,
            is_admin=is_admin
        )

    except OAuthStateValidationError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "code": "invalid_state",
                "message": str(e)
            }
        )
    except OAuthTokenExchangeError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "code": "token_exchange_failed",
                "message": str(e)
            }
        )
    except OAuthTokenVerificationError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "code": "token_verification_failed",
                "message": str(e)
            }
        )
    except AccountLinkingError as e:
        error_message = str(e)

        # Check if this is an ACCOUNT_RECOVERABLE error (soft-deleted OAuth account)
        if "ACCOUNT_RECOVERABLE|" in error_message:
            # Parse the permanent deletion date from the error message
            parts = error_message.split("ACCOUNT_RECOVERABLE|")
            permanent_deletion_date = parts[1] if len(parts) > 1 else None

            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail={
                    "code": "ACCOUNT_RECOVERABLE",
                    "message": "This account was previously deleted and can be restored.",
                    "permanent_deletion_date": permanent_deletion_date,
                    "restore_endpoint": "/api/v1/auth/restore-account"
                }
            )

        # Regular account linking error (email exists with password auth)
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail={
                "code": "account_linking_required",
                "message": error_message
            }
        )
    except HTTPException:
        # Re-raise HTTPExceptions (e.g. missing_id_token) without wrapping
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "code": "callback_failed",
                "message": f"OAuth callback failed: {str(e)}"
            }
        )
