"""
Privacy Service

Business logic for GDPR Article 15 data export.
Aggregates user data from all repositories into a single
machine-readable export.
"""

import hashlib
import logging
from datetime import datetime, timedelta, timezone
from typing import Optional
from uuid import UUID

from src.core.config import settings
from src.models.audit import AuditEventType, AuditOperation
from src.repositories.auth_repository import AuthRepository
from src.repositories.context_repository import ContextRepository
from src.repositories.oauth_repository import OAuthRepository
from src.repositories.profile_repository import ProfileRepository
from src.services.audit_service import AuditService

logger = logging.getLogger(__name__)


class PrivacyServiceError(Exception):
    """Base exception for privacy service errors."""
    pass


class ProfileNotFoundError(PrivacyServiceError):
    """Raised when the requested profile does not exist."""
    pass


class AccountAlreadyDeletedError(PrivacyServiceError):
    """Raised when a deletion request targets an already-deleted account."""
    pass


GDPR_METADATA = {
    "processing_purposes": [
        "Identity management and multi-context profile presentation",
        "Authentication and account security",
        "OAuth 2.1 authorization and third-party access control",
        "Audit logging for security and accountability",
    ],
    "retention_periods": {
        "profile_data": "Retained until account deletion; 30-day recovery window after soft delete",
        "authentication_data": "Retained while account is active; 30-day recovery window after soft delete",
        "oauth_consents": "Retained for the duration of the consent; withdrawn consents kept for audit purposes",
        "audit_logs": "7-year retention for legal and security accountability",
    },
    "data_subject_rights": [
        "Right of access (Article 15) - this export",
        "Right to rectification (Article 16) - update profile via API",
        "Right to erasure (Article 17) - delete account via API with 30-day recovery",
        "Right to data portability (Article 20) - this JSON export",
        "Right to object (Article 21) - withdraw OAuth consents via API",
    ],
    "data_sources": [
        "Data provided directly by the user during registration and profile management",
        "Authentication events generated by user actions (login, password changes)",
        "OAuth consent records created when authorizing third-party applications",
    ],
    "recipients_or_categories": [
        "Third-party applications authorized via OAuth 2.1 (scope-limited access)",
        "System administrators for security and support purposes",
    ],
    "automated_decision_making": (
        "No automated decision-making or profiling is performed on user data."
    ),
}


class PrivacyService:
    """Service for GDPR-inspired privacy operations."""

    def __init__(
        self,
        profile_repo: ProfileRepository,
        context_repo: ContextRepository,
        auth_repo: AuthRepository,
        oauth_repo: OAuthRepository,
        audit_service: Optional[AuditService] = None,
    ):
        self.profile_repo = profile_repo
        self.context_repo = context_repo
        self.auth_repo = auth_repo
        self.oauth_repo = oauth_repo
        self.audit_service = audit_service

    def export_user_data(
        self,
        user_id: UUID,
        actor_id: Optional[UUID] = None,
        ip_address: Optional[str] = None,
        user_agent: Optional[str] = None,
    ) -> dict:
        """
        Export all personal data for a user per GDPR Article 15.

        Aggregates data from profile, identity names, context profiles,
        authentication metadata, and OAuth consents. Excludes security-sensitive
        fields (password hashes, tokens) and audit logs.

        Args:
            user_id: Data subject UUID
            actor_id: UUID of the actor requesting the export
            ip_address: Requester IP address (for audit)
            user_agent: Requester user agent (for audit)

        Returns:
            Dict containing all exportable user data with GDPR metadata

        Raises:
            ProfileNotFoundError: If the user profile does not exist
        """
        # Fetch base profile
        profile = self.profile_repo.get_profile_by_id(user_id)
        if not profile:
            raise ProfileNotFoundError(
                f"Profile not found for user_id: {user_id}"
            )

        # Fetch all identity names including deprecated (GDPR requires all data)
        identity_names = self.profile_repo.get_identity_names(
            user_id, include_deprecated=True
        )

        # Fetch all context profiles including inactive
        context_profiles = self.context_repo.get_user_context_profiles(
            user_id, include_inactive=True
        )

        # Fetch auth metadata
        auth_user = self.auth_repo.get_by_user_id(str(user_id))

        # Fetch all OAuth consents (active and withdrawn)
        oauth_consents = self.oauth_repo.get_user_consents(user_id)

        # Build authentication export (exclude sensitive fields)
        auth_export = None
        if auth_user:
            auth_export = {
                "email": auth_user.email,
                "is_email_verified": auth_user.is_email_verified,
                "email_verified_at": auth_user.email_verified_at,
                "last_login_at": auth_user.last_login_at,
                "password_changed_at": auth_user.password_changed_at,
                "is_admin": auth_user.is_admin,
                "created_at": auth_user.created_at,
            }

        # Build consent export (exclude IP and user_agent for privacy)
        consents_export: list[dict] = []
        for consent in oauth_consents:
            consents_export.append({
                "id": consent.id,
                "client_id": consent.client_id,
                "granted_scopes": consent.granted_scopes or [],
                "context_profile_id": consent.context_profile_id,
                "consent_method": (
                    consent.consent_method.value
                    if hasattr(consent.consent_method, "value")
                    else str(consent.consent_method)
                ),
                "granted_at": consent.granted_at,
                "expires_at": consent.expires_at,
                "withdrawn_at": consent.withdrawn_at,
            })

        now = datetime.now(timezone.utc)

        export = {
            "export_metadata": {
                "exported_at": now,
                "user_id": user_id,
                "format_version": "1.0",
                "legal_basis": "GDPR Article 15 - Right of access",
            },
            "profile": {
                "user_id": profile.user_id,
                "account_type": (
                    profile.account_type.value
                    if hasattr(profile.account_type, "value")
                    else str(profile.account_type)
                ),
                "legal_name": profile.legal_name,
                "primary_email": profile.primary_email,
                "primary_phone": profile.primary_phone,
                "preferred_language": profile.preferred_language,
                "valid_from": profile.valid_from,
                "valid_to": profile.valid_to,
                "created_at": profile.created_at,
                "updated_at": profile.updated_at,
            },
            "identity_names": [
                {
                    "id": name.id,
                    "name_type": (
                        name.name_type.value
                        if hasattr(name.name_type, "value")
                        else str(name.name_type)
                    ),
                    "name_value": name.name_value,
                    "is_primary": name.is_primary,
                    "is_deprecated": name.is_deprecated,
                    "visibility_level": (
                        name.visibility_level.value
                        if hasattr(name.visibility_level, "value")
                        else str(name.visibility_level)
                    ),
                    "context_id": name.context_id,
                    "valid_from": name.valid_from,
                    "valid_to": name.valid_to,
                    "created_at": name.created_at,
                    "updated_at": name.updated_at,
                }
                for name in identity_names
            ],
            "context_profiles": [
                {
                    "id": ctx.id,
                    "context_type": (
                        ctx.context_type.value
                        if hasattr(ctx.context_type, "value")
                        else str(ctx.context_type)
                    ),
                    "context_name": ctx.context_name,
                    "display_name_override": ctx.display_name_override,
                    "email_override": ctx.email_override,
                    "phone_override": ctx.phone_override,
                    "bio": ctx.bio,
                    "is_active": ctx.is_active,
                    "valid_from": ctx.valid_from,
                    "valid_to": ctx.valid_to,
                    "created_at": ctx.created_at,
                    "updated_at": ctx.updated_at,
                }
                for ctx in context_profiles
            ],
            "authentication": auth_export,
            "oauth_consents": consents_export,
            "gdpr_metadata": GDPR_METADATA,
        }

        # Log the export event
        if self.audit_service:
            self.audit_service.log_event(
                event_type=AuditEventType.data_export,
                user_id=user_id,
                actor_id=actor_id or user_id,
                resource_type="user_data",
                resource_id=str(user_id),
                operation=AuditOperation.create,
                ip_address=ip_address,
                user_agent=user_agent,
                legal_basis="gdpr_art_15_access",
            )

        return export

    def soft_delete_account(
        self,
        user_id: UUID,
        actor_id: Optional[UUID] = None,
        ip_address: Optional[str] = None,
        user_agent: Optional[str] = None,
    ) -> dict:
        """
        Soft delete user account and all associated data.

        Sets deleted_at on auth_users, base_profiles, and context_profiles.
        Revokes all OAuth tokens and withdraws consents.
        Creates an immutable audit log entry.

        Args:
            user_id: Data subject UUID
            actor_id: UUID of the actor requesting deletion
            ip_address: Requester IP address (for audit)
            user_agent: Requester user agent (for audit)

        Returns:
            Dict with deletion scheduling information

        Raises:
            ProfileNotFoundError: If the user profile does not exist
            AccountAlreadyDeletedError: If the account is already soft-deleted
        """
        # Verify user exists
        profile = self.profile_repo.get_profile_by_id(user_id)
        if not profile:
            raise ProfileNotFoundError(
                f"Profile not found for user_id: {user_id}"
            )

        auth_user = self.auth_repo.get_by_user_id(str(user_id))
        if not auth_user:
            raise ProfileNotFoundError(
                f"Auth user not found for user_id: {user_id}"
            )

        if auth_user.deleted_at is not None:
            raise AccountAlreadyDeletedError(
                f"Account already deleted for user_id: {user_id}"
            )

        now = datetime.now(timezone.utc)
        retention_days = settings.DELETION_RETENTION_DAYS
        permanent_deletion_date = now + timedelta(days=retention_days)

        # Soft delete auth user
        self.auth_repo.soft_delete(str(user_id))

        # Soft delete base profile
        self.profile_repo.soft_delete_profile(user_id)

        # Soft delete all context profiles
        self.context_repo.soft_delete_user_contexts(user_id)

        # Revoke all OAuth access tokens
        self.oauth_repo.revoke_all_user_tokens(user_id)

        # Revoke all OAuth refresh tokens
        self.oauth_repo.revoke_all_user_refresh_tokens(user_id)

        # Withdraw all consents
        self.oauth_repo.withdraw_all_user_consents(user_id)

        # Audit log
        if self.audit_service:
            self.audit_service.log_event(
                event_type=AuditEventType.account_deletion_requested,
                user_id=user_id,
                actor_id=actor_id or user_id,
                resource_type="account",
                resource_id=str(user_id),
                operation=AuditOperation.delete,
                changes={
                    "retention_days": retention_days,
                    "permanent_deletion_date": permanent_deletion_date.isoformat(),
                },
                ip_address=ip_address,
                user_agent=user_agent,
                legal_basis="gdpr_art_17_erasure",
            )

        return {
            "status": "scheduled",
            "deletion_scheduled_at": now.isoformat(),
            "permanent_deletion_date": permanent_deletion_date.isoformat(),
            "message": (
                "Account scheduled for deletion. You can restore your account "
                f"by registering again with the same email within {retention_days} days."
            ),
        }

    def get_deletion_status(
        self,
        user_id: UUID,
    ) -> dict:
        """
        Get the current deletion status of a user account.

        Args:
            user_id: Data subject UUID

        Returns:
            Dict with status: "active", "scheduled", or "purged"
        """
        # Check for active account
        auth_user = self.auth_repo.get_by_user_id(str(user_id))
        if auth_user:
            return {"status": "active"}

        # Check for soft-deleted account (including deleted)
        auth_user_deleted = self.auth_repo.get_by_email_including_deleted(
            ""  # placeholder
        )
        # Better approach: query by user_id without deleted_at filter
        from sqlalchemy import select
        from src.models.auth import AuthUser
        stmt = select(AuthUser).where(AuthUser.user_id == str(user_id))
        result = self.auth_repo.db.execute(stmt)
        auth_user_any = result.scalars().first()

        if auth_user_any and auth_user_any.deleted_at is not None:
            retention_days = settings.DELETION_RETENTION_DAYS
            deleted_at = auth_user_any.deleted_at
            # Normalize timezone (SQLite may strip tzinfo)
            if deleted_at.tzinfo is None:
                deleted_at = deleted_at.replace(tzinfo=timezone.utc)
            permanent_date = deleted_at + timedelta(days=retention_days)
            return {
                "status": "scheduled",
                "deletion_scheduled_at": deleted_at.isoformat(),
                "permanent_deletion_date": permanent_date.isoformat(),
            }

        return {"status": "purged"}

    def purge_expired_accounts(
        self,
        retention_days: Optional[int] = None,
    ) -> int:
        """
        Permanently delete accounts whose grace period has expired.

        Args:
            retention_days: Override for retention period (uses config default)

        Returns:
            Number of accounts permanently purged
        """
        if retention_days is None:
            retention_days = settings.DELETION_RETENTION_DAYS

        expired_users = self.auth_repo.get_expired_soft_deleted_users(
            retention_days
        )

        purged_count = 0
        for auth_user in expired_users:
            user_id_str = str(auth_user.user_id)
            # Hash the user_id for audit (no PII in purge events)
            hashed_id = hashlib.sha256(user_id_str.encode()).hexdigest()[:16]

            # Hard delete profile (CASCADE handles children)
            self.profile_repo.hard_delete_profile(auth_user.user_id)

            # Hard delete auth user
            self.auth_repo.hard_delete(user_id_str)

            # Audit log with hashed identifier (no PII)
            if self.audit_service:
                self.audit_service.log_event(
                    event_type=AuditEventType.account_permanently_purged,
                    user_id=None,  # SET NULL after purge
                    actor_id=None,
                    resource_type="account",
                    resource_id=f"purged:{hashed_id}",
                    operation=AuditOperation.delete,
                    changes={
                        "retention_days": retention_days,
                        "purged_at": datetime.now(timezone.utc).isoformat(),
                    },
                    legal_basis="gdpr_art_17_retention_expiry",
                )

            purged_count += 1

        logger.info(
            "Purged %d expired accounts (retention: %d days)",
            purged_count,
            retention_days,
        )
        return purged_count
