"""
Privacy Service

Business logic for GDPR Article 15 data export.
Aggregates user data from all repositories into a single
machine-readable export.
"""

import logging
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from src.models.audit import AuditEventType, AuditOperation
from src.repositories.auth_repository import AuthRepository
from src.repositories.context_repository import ContextRepository
from src.repositories.oauth_repository import OAuthRepository
from src.repositories.profile_repository import ProfileRepository
from src.services.audit_service import AuditService

logger = logging.getLogger(__name__)


class PrivacyServiceError(Exception):
    """Base exception for privacy service errors."""
    pass


class ProfileNotFoundError(PrivacyServiceError):
    """Raised when the requested profile does not exist."""
    pass


GDPR_METADATA = {
    "processing_purposes": [
        "Identity management and multi-context profile presentation",
        "Authentication and account security",
        "OAuth 2.1 authorization and third-party access control",
        "Audit logging for security and accountability",
    ],
    "retention_periods": {
        "profile_data": "Retained until account deletion; 30-day recovery window after soft delete",
        "authentication_data": "Retained while account is active; 30-day recovery window after soft delete",
        "oauth_consents": "Retained for the duration of the consent; withdrawn consents kept for audit purposes",
        "audit_logs": "7-year retention for legal and security accountability",
    },
    "data_subject_rights": [
        "Right of access (Article 15) - this export",
        "Right to rectification (Article 16) - update profile via API",
        "Right to erasure (Article 17) - delete account via API with 30-day recovery",
        "Right to data portability (Article 20) - this JSON export",
        "Right to object (Article 21) - withdraw OAuth consents via API",
    ],
    "data_sources": [
        "Data provided directly by the user during registration and profile management",
        "Authentication events generated by user actions (login, password changes)",
        "OAuth consent records created when authorizing third-party applications",
    ],
    "recipients_or_categories": [
        "Third-party applications authorized via OAuth 2.1 (scope-limited access)",
        "System administrators for security and support purposes",
    ],
    "automated_decision_making": (
        "No automated decision-making or profiling is performed on user data."
    ),
}


class PrivacyService:
    """Service for GDPR-inspired privacy operations."""

    def __init__(
        self,
        profile_repo: ProfileRepository,
        context_repo: ContextRepository,
        auth_repo: AuthRepository,
        oauth_repo: OAuthRepository,
        audit_service: Optional[AuditService] = None,
    ):
        self.profile_repo = profile_repo
        self.context_repo = context_repo
        self.auth_repo = auth_repo
        self.oauth_repo = oauth_repo
        self.audit_service = audit_service

    def export_user_data(
        self,
        user_id: UUID,
        actor_id: Optional[UUID] = None,
        ip_address: Optional[str] = None,
        user_agent: Optional[str] = None,
    ) -> dict:
        """
        Export all personal data for a user per GDPR Article 15.

        Aggregates data from profile, identity names, context profiles,
        authentication metadata, and OAuth consents. Excludes security-sensitive
        fields (password hashes, tokens) and audit logs.

        Args:
            user_id: Data subject UUID
            actor_id: UUID of the actor requesting the export
            ip_address: Requester IP address (for audit)
            user_agent: Requester user agent (for audit)

        Returns:
            Dict containing all exportable user data with GDPR metadata

        Raises:
            ProfileNotFoundError: If the user profile does not exist
        """
        # Fetch base profile
        profile = self.profile_repo.get_profile_by_id(user_id)
        if not profile:
            raise ProfileNotFoundError(
                f"Profile not found for user_id: {user_id}"
            )

        # Fetch all identity names including deprecated (GDPR requires all data)
        identity_names = self.profile_repo.get_identity_names(
            user_id, include_deprecated=True
        )

        # Fetch all context profiles including inactive
        context_profiles = self.context_repo.get_user_context_profiles(
            user_id, include_inactive=True
        )

        # Fetch auth metadata
        auth_user = self.auth_repo.get_by_user_id(str(user_id))

        # Fetch all OAuth consents (active and withdrawn)
        oauth_consents = self.oauth_repo.get_user_consents(user_id)

        # Build authentication export (exclude sensitive fields)
        auth_export = None
        if auth_user:
            auth_export = {
                "email": auth_user.email,
                "is_email_verified": auth_user.is_email_verified,
                "email_verified_at": auth_user.email_verified_at,
                "last_login_at": auth_user.last_login_at,
                "password_changed_at": auth_user.password_changed_at,
                "is_admin": auth_user.is_admin,
                "created_at": auth_user.created_at,
            }

        # Build consent export (exclude IP and user_agent for privacy)
        consents_export = []
        for consent in oauth_consents:
            consents_export.append({
                "id": consent.id,
                "client_id": consent.client_id,
                "granted_scopes": consent.granted_scopes or [],
                "context_profile_id": consent.context_profile_id,
                "consent_method": (
                    consent.consent_method.value
                    if hasattr(consent.consent_method, "value")
                    else str(consent.consent_method)
                ),
                "granted_at": consent.granted_at,
                "expires_at": consent.expires_at,
                "withdrawn_at": consent.withdrawn_at,
            })

        now = datetime.now(timezone.utc)

        export = {
            "export_metadata": {
                "exported_at": now,
                "user_id": user_id,
                "format_version": "1.0",
                "legal_basis": "GDPR Article 15 - Right of access",
            },
            "profile": {
                "user_id": profile.user_id,
                "account_type": (
                    profile.account_type.value
                    if hasattr(profile.account_type, "value")
                    else str(profile.account_type)
                ),
                "legal_name": profile.legal_name,
                "primary_email": profile.primary_email,
                "primary_phone": profile.primary_phone,
                "preferred_language": profile.preferred_language,
                "valid_from": profile.valid_from,
                "valid_to": profile.valid_to,
                "created_at": profile.created_at,
                "updated_at": profile.updated_at,
            },
            "identity_names": [
                {
                    "id": name.id,
                    "name_type": (
                        name.name_type.value
                        if hasattr(name.name_type, "value")
                        else str(name.name_type)
                    ),
                    "name_value": name.name_value,
                    "is_primary": name.is_primary,
                    "is_deprecated": name.is_deprecated,
                    "visibility_level": (
                        name.visibility_level.value
                        if hasattr(name.visibility_level, "value")
                        else str(name.visibility_level)
                    ),
                    "context_id": name.context_id,
                    "valid_from": name.valid_from,
                    "valid_to": name.valid_to,
                    "created_at": name.created_at,
                    "updated_at": name.updated_at,
                }
                for name in identity_names
            ],
            "context_profiles": [
                {
                    "id": ctx.id,
                    "context_type": (
                        ctx.context_type.value
                        if hasattr(ctx.context_type, "value")
                        else str(ctx.context_type)
                    ),
                    "context_name": ctx.context_name,
                    "display_name_override": ctx.display_name_override,
                    "email_override": ctx.email_override,
                    "phone_override": ctx.phone_override,
                    "bio": ctx.bio,
                    "is_active": ctx.is_active,
                    "valid_from": ctx.valid_from,
                    "valid_to": ctx.valid_to,
                    "created_at": ctx.created_at,
                    "updated_at": ctx.updated_at,
                }
                for ctx in context_profiles
            ],
            "authentication": auth_export,
            "oauth_consents": consents_export,
            "gdpr_metadata": GDPR_METADATA,
        }

        # Log the export event
        if self.audit_service:
            self.audit_service.log_event(
                event_type=AuditEventType.data_export,
                user_id=user_id,
                actor_id=actor_id or user_id,
                resource_type="user_data",
                resource_id=str(user_id),
                operation=AuditOperation.create,
                ip_address=ip_address,
                user_agent=user_agent,
                legal_basis="gdpr_art_15_access",
            )

        return export
